import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StoreProvider from "@/store/StoreProvider";

import NavBar from "./_layout/NavBar";
import Footer from "./_layout/Footer";
import { ToastContainer } from "react-toastify";

import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <StoreProvider>
          <div className="min-vh-100 d-flex flex-column">
            <NavBar />
            <div className="pt-5 flex-fill">
              {children}
            </div>
            <Footer />
          </div>
        </StoreProvider>
        <ToastContainer />
      </body>
    </html>
  );
}